날짜 | 범위
--- | ---
1/22 | 9.4 private, protected 프로퍼티와 메서드 ~ 10.1 'try..catch'와 에러 핸들링

### private, protected 프로퍼티와 메서드
- `public`은 외부 인터페이스이고 외부에서 접근이 가능하다.
- `private`는 내부 인터페이스이고 내부 클래스에서만 접근이 가능하다.(캡슐화)
- `protected`는 내부 클래스와 자식 클래스에서 접근이 가능하지만 자바스크립트에서 지원하지 않으므로 이를 모방해서 사용한다.
- 외부 접근이 불가능한 프로퍼티 명 앞에는 대개 밑줄(_)이 붙는다.(보통은 `protected`)
- `protected` 필드는 상속된다.
- `private` 프로퍼티, 메서드는 앞에 #을 붙이며 클래스 외부와 자손 클래스에서 접근할 수 없다.
```javascript
class Fruit(){
  _name = '';  //pritected 프로퍼티
  #price = 0;  //private 프로퍼티
  
  get price() {
    return this.#price;
  }
  set price(value) {
    this.#price = value;
  }
}

let apple = new Fruit();
apple.price = 100;

console.log(apple.price);  //100 (public과 상충하지 않는다)
console.log(apple.#price);  //error
```

### 내장 클래스 확장하기
```javascript
class PowerArray extends Array {
  isEmpty(){
    return this.length === 0;
  }
  
  //특수 정적 getter인 Symbol.species를 추가하면 map, filter등의 메서드를 호출할때 만들어지는 개체의 생성자를 지정할 수 있다.
  static get [Symbol.species]() {
    return Array;
  }
}

let arr = new PowerArray(1, 2, 3);
console.log(arr.isEmpty());  //false

let filterArr = arr.filter(item => item > 2);  //filter의 반환값은 지정된 Array
console.log(filterArr.isEmpty());  //Array의 인스턴스이므로 error
```

- 내장 클래스는 정적 메서드를 상속받지 못한다.
- `Array`와 `Date`는 `Object`를 상속받기 때문에 `Object.prototype`에 구현된 메서드를 사용할 수 있다. 하지만 `Array.[[Prototype]]`와 `Date.[[Prototype]]`은 `Object`를 참조하지 않기때문에 `Array.keys()`나 `Date.keys()`같은 정적 메서드를 인스턴스에서 사용할 수 없다.

### 'instanceof'로 클래스 확인하기
- `obj instanceof Class` 로 객체가 특정 클래스에 속하는지, 상속하는지 등을 알 수 있다.
```javascript
class Fruit() { ... }

let fruit = new Fruit();

alert(fruit instanceof Fruit());  //true
alert(fruit instanceof Object());  //true
alert(new Fruit() instanceof Fruit);  //true

class Test(){
  //instanceof의 동작을 커스터마이징 할 수 있다.
  static [Symbol.hasInstance](obj){
    if(obj.isTest) return true;
  }
}

let test = { isTest: true };
alert(test instanceof Test);  //true

//toString 커스터마이징 하기
let user = {
  [Symbol.toStringTag]: 'User'
};

alert( {}.toString.cal(user) );  //[object user]
```

### 믹스인
- 다른 클래스를 상속받을 필요 없이 이들 클래스에 구현되어 있는 메서드를 담고있는 클래스를 믹스인(mixin)이라고 한다.
```javascript
let test = {
  start(){
    alert(`start ${this.name}`);
  }
};

class User {
  constructor(name){
    this.name = name;
  }
}

//메서드 복사
Object.assign(User.prototype, test);
new User('testUser').start();  //start testUser 출력
```

### 'try..catch'와 에러 핸들링
```javascript
try {
  if(!name){  //name필드가 없으면 에러 던지기
    throw new Error('name필드가 없는 에러 발생');
  }
  
  testCode;  //에러발생 부분
  start();  //위 코드에서 에러가 발생하였으므로 실행이 안됨
  
} catch(err) {  //에러 객체를 얻을 수 있음((err) 생략 가능)
  
  //에러 핸들링
  console.log(err.name, err.message, err.stack);
  
  if( err instanceof ReferenceError ){
      alert('ReferenceError !');
  } else {
    //try..catch문 바깥으로 에러 던지기
    //해당 코드를 호출한 다른곳에서 try..catch로 감싸고 있으면 에러처리가 가능하고 없으면 스크립트가 중단됨
    throw err;  
  }
  
} finally {
  //정상처리되거나 에러처리되거나 상관없이 항상 실행되는 코드
}
```

- `try..catch`는 오직 런타임 에러에만 동작하므로 유효한 코드에서 발생하는 에러만 처리할 수 있다.(런타임 에러)
- `try..catch` 내부에 `setTimeout`같은 비동기 코드를 넣으면 에러를 잡을 수 없으므로 `try..catch` 바깥으로 감싸야 한다.
- `catch`절이 없는 `try..finally`절도 가능하다.
- 브라우저에서는 처리하지 못한 에러를 확인하기 위해 `window.onerror` 프로퍼티에 함수를 할당하기도 한다.
